ru.practicum.client:
  host: stats-server
  port: 9090

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://ewm-db:5432/ewmDataBase
    username: user
    password: password