CREATE TABLE IF NOT EXISTS users (
    user_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS categories (
    category_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS events (
    event_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    annotation VARCHAR(100),
    title VARCHAR(50) NOT NULL,
    description VARCHAR(500) NOT NULL,
    category_id INT REFERENCES categories(category_id) NOT NULL,
    createdOn TIMESTAMP NOT NULL,
    publishedOn TIMESTAMP,
    eventDate TIMESTAMP NOT NULL,
    user_id INT REFERENCES users(user_id),
    lot FLOAT NOT NULL,
    lon FLOAT NOT NULL,
    paid BOOLEAN,
    participantLimit INT DEFAULT 0,
    confirmRequests INT,
    requestModeration BOOLEAN DEFAULT true,
    state VARCHAR(30)
);

CREATE TABLE IF NOT EXISTS compilations (
    compilation_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pinned BOOLEAN,
    title VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS compilations_events (
    compilation_id INT REFERENCES compilations(compilation_id) NOT NULL,
    event_id INT REFERENCES events(event_id) NOT NULL
);