spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://stats-db:5432/statsDataBase
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always

server:
  port: 9090